FROM nginx:alpine
RUN apk add --no-cache openssl
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY generate-cert.sh /docker-entrypoint.d/01-generate-cert.sh
RUN chmod +x /docker-entrypoint.d/01-generate-cert.sh
